[project]
name = "kjpdk-docs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "kjpdk", email = "kjp@bartogh.dk" }
]
requires-python = ">=3.14"
dependencies = [
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.7.6",
]

[build-system]
requires = ["uv_build>=0.11.18,<0.12.0"]
build-backend = "uv_build"
